### ISSUE TITLE
how it works

### ISSUE THREAD

**Issue by Sarahphp1** [chx/webform_product#1]
Hi there
I am new to Drupal.
So, if you could give me a brief explanation of how this module works, I would really appreciate it.
My dev site is on drupal 8. I have commerce 2.0 and webforms 8.x-5.0-beta13
I have been struggling to add an entity reference field of commerce porducts to webforms, but it only shows the products but not thier variations and price.
Also, how to have webforms submit button takes you to the checkout process (shopping cart)?

Thanks

**Comment by samayo** [comment]
@Sarahphp1 Did you get how it works? I can't figure it out

**Comment by Sarahphp1** [comment]
Unfortunetly, I could not.
I only saw 'Price' field added to every webform element. And that was it!
I had to uninstall it and found another way around it.

**Comment by samayo** [comment]
Thanks, I did the same.

**Comment by Sarahphp1** [comment]
You are welcome.
