### ISSUE TITLE
Fix for outdated commerce_store.store_context

### ISSUE THREAD

**Issue by shabananavas** [chx/webform_product#3]
Need to fix the fatal error that is thrown because commerce has changed commerce_store.store_context to commerce_store.current_store. Also, need to add another fix that doesn't add the product to the cart when $value is just a string.

**Comment by shabananavas** [comment]
PR here: https://github.com/chx/webform_product/pull/4

**Comment by chx** [comment]
Thanks, this got fixed with the latest commit.
